{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram-alerter.fullname" . }}
  labels:
    {{- include "telegram-alerter.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ required "secret.botToken is required when secret.create is true" .Values.secret.botToken | quote }}
  TELEGRAM_CHAT_ID: {{ required "secret.chatId is required when secret.create is true" .Values.secret.chatId | quote }}
  AUTH_TOKEN: {{ required "secret.authToken is required when secret.create is true" .Values.secret.authToken | quote }}
{{- end -}}
